### ISSUE TITLE
Webfont Ligature Support

### ISSUE THREAD

**Issue by stephenway** [sharanda/manrope#11]
Hey, I'm trying to get ligatures working with the CSS property `font-variant-ligatures: normal;` while using the woff2 files loaded from the css file in this repository and can't seem to get it to work on Chrome.
Is this not baked into the woff2 files yet?

Thanks

**Comment by sharanda** [comment]
@stephenway works well in Chrome on my website. I'm using exact same files from this repository. Which ligature you're experiencing problems with?
<img width="201" alt="Screenshot 2019-04-10 at 8 30 47 AM" src="https://user-images.githubusercontent.com/32507483/55843504-388e7800-5b6b-11e9-8159-57fc73b178b0.png">

**Comment by stephenway** [comment]
@sharanda I can reproduce your matters example on my project, however I think I was expecting "fi" to be a ligature when I opened this. Since I can reproduce your example, I'm just going to close this and move on for now. Thanks

**Comment by tettoffensive** [comment]
I have figured out how to reproduce this. If you have any letter spacing at all the ligatures do not show up.

It took me a while to figure out why my buttons weren't combining "->" into an arrow. As soon as I set the letter spacing to zero however, problem solved.

I'm not sure if there's anything the font can do to fix this or maybe a css setting I don't know about. Otherwise, got to wrap those ligatures in spans with letter spacing 0.
