### ISSUE TITLE
How to subset this font?

### ISSUE THREAD

**Issue by Floriferous** [sharanda/manrope#46]
Hi, I wonder what the most appropriate way to subset this font is? I've tried multiple tools online so far, but they all seem to strip some of the advanced features of this font (like `font-variant-numeric`). Could this be done directly via CSS (we're using this font on the web)?

We only need to support a couple of western european languages, so I'd like to reduce the size of the variable font.

I'm a noob with fonts, and even more variable fonts, so excuse me if this is well explained in a guide somewhere. I mostly found tutorials involving python libraries, am wondering whether there is a simpler way.

**Comment by sharanda** [comment]
@Floriferous I believe the only appropriate way to erase not needed glyphs is to download Glyphs app 30 days trial version: https://glyphsapp.com/buy and Manrope font source file: https://github.com/sharanda/manrope/tree/master/source then, delete letters you don't need and export again :-)

P.S.: previously I tried to export different versions to save data. But it was very troublesome, while difference in WOFF2 format was only ~5-15kb. I guess because of components.

Hope it helps.
